package com.google.android.gms.nearby;

import com.google.android.gms.common.Feature;

/* compiled from: com.google.android.gms:play-services-nearby@@18.7.0 */
/* loaded from: classes4.dex */
public final class zza {
    public static final Feature zzA;
    public static final Feature zzB;
    public static final Feature zzC;
    public static final Feature zzD;
    public static final Feature zzE;
    public static final Feature zzF;
    public static final Feature zzG;
    public static final Feature zzH;
    public static final Feature zzI;
    public static final Feature zzJ;
    public static final Feature zzK;
    public static final Feature zzL;
    public static final Feature zzM;
    public static final Feature zzN;
    public static final Feature zzO;
    public static final Feature zzP;
    public static final Feature zzQ;
    public static final Feature zzR;
    public static final Feature zzS;
    public static final Feature zzT;
    public static final Feature zzU;
    public static final Feature zzV;
    public static final Feature zzW;
    public static final Feature zzX;
    public static final Feature zzY;
    public static final Feature zzZ;
    public static final Feature zza;
    public static final Feature zzaa;
    public static final Feature zzab;
    public static final Feature zzac;
    public static final Feature zzad;
    public static final Feature[] zzae;
    public static final Feature zzb;
    public static final Feature zzc;
    public static final Feature zzd;
    public static final Feature zze;
    public static final Feature zzf;
    public static final Feature zzg;
    public static final Feature zzh;
    public static final Feature zzi;
    public static final Feature zzj;
    public static final Feature zzk;
    public static final Feature zzl;
    public static final Feature zzm;
    public static final Feature zzn;
    public static final Feature zzo;
    public static final Feature zzp;
    public static final Feature zzq;
    public static final Feature zzr;
    public static final Feature zzs;
    public static final Feature zzt;
    public static final Feature zzu;
    public static final Feature zzv;
    public static final Feature zzw;
    public static final Feature zzx;
    public static final Feature zzy;
    public static final Feature zzz;

    static {
        Feature feature = new Feature("nearby_sharing", 38L);
        zza = feature;
        Feature feature2 = new Feature("nearby_sharing_allow_permission_auto", 1L);
        zzb = feature2;
        Feature feature3 = new Feature("nearby_sharing_get_phone_numbers", 1L);
        zzc = feature3;
        Feature feature4 = new Feature("nearby_sharing_ignore_consent", 2L);
        zzd = feature4;
        Feature feature5 = new Feature("nearby_sharing_phonesky", 6L);
        zze = feature5;
        Feature feature6 = new Feature("nearby_connections", 3L);
        zzf = feature6;
        Feature feature7 = new Feature("nearby_connections_v2", 2L);
        zzg = feature7;
        Feature feature8 = new Feature("nearby_connections_v3", 1L);
        zzh = feature8;
        Feature feature9 = new Feature("nearby_exposure_notification", 3L);
        zzi = feature9;
        Feature feature10 = new Feature("nearby_exposure_notification_1p", 1L);
        zzj = feature10;
        Feature feature11 = new Feature("nearby_exposure_notification_get_version", 1L);
        zzk = feature11;
        Feature feature12 = new Feature("nearby_exposure_notification_get_calibration_confidence", 1L);
        zzl = feature12;
        Feature feature13 = new Feature("nearby_exposure_notification_get_day_summaries", 1L);
        zzm = feature13;
        Feature feature14 = new Feature("nearby_exposure_notification_get_status", 1L);
        zzn = feature14;
        Feature feature15 = new Feature("nearby_exposure_notification_diagnosis_keys_data_mapping", 1L);
        zzo = feature15;
        Feature feature16 = new Feature("nearby_exposure_notification_diagnosis_key_file_supplier", 1L);
        zzp = feature16;
        Feature feature17 = new Feature("nearby_exposure_notification_package_configuration", 1L);
        zzq = feature17;
        Feature feature18 = new Feature("nearby_exposure_notification_preauthorize_key_release", 1L);
        zzr = feature18;
        Feature feature19 = new Feature("nearby_exposure_notification_preauthorize_key_release_for_self_report", 1L);
        zzs = feature19;
        Feature feature20 = new Feature("nearby_fast_pair", 4L);
        zzt = feature20;
        Feature feature21 = new Feature("nearby_fast_pair_sass", 4L);
        zzu = feature21;
        Feature feature22 = new Feature("nearby_fast_pair_validator", 1L);
        zzv = feature22;
        Feature feature23 = new Feature("nearby_fast_pair_wear_os", 3L);
        zzw = feature23;
        Feature feature24 = new Feature("nearby_fast_pair_wear_peripheral", 1L);
        zzx = feature24;
        Feature feature25 = new Feature("nearby_fast_pair_wear_peripheral_notify_disable", 1L);
        zzy = feature25;
        Feature feature26 = new Feature("nearby_presence", 5L);
        zzz = feature26;
        Feature feature27 = new Feature("nearby_presence_broadcast_request_api", 1L);
        zzA = feature27;
        Feature feature28 = new Feature("nearby_presence_discovery_request_api", 2L);
        zzB = feature28;
        Feature feature29 = new Feature("nearby_presence_format_medium_support", 1L);
        zzC = feature29;
        Feature feature30 = new Feature("nearby_presence_get_device_account_id", 1L);
        zzD = feature30;
        Feature feature31 = new Feature("nearby_presence_get_version", 1L);
        zzE = feature31;
        Feature feature32 = new Feature("nearby_presence_reset", 1L);
        zzF = feature32;
        Feature feature33 = new Feature("nearby_presence_sync", 1L);
        zzG = feature33;
        Feature feature34 = new Feature("nearby_connections_get_local_endpoint_id", 1L);
        zzH = feature34;
        Feature feature35 = new Feature("nearby_connections_register_device_provider", 1L);
        zzI = feature35;
        Feature feature36 = new Feature("nearby_connections_update_advertising_options", 1L);
        zzJ = feature36;
        Feature feature37 = new Feature("nearby_connections_update_connection_options", 1L);
        zzK = feature37;
        Feature feature38 = new Feature("nearby_connections_update_discovery_options", 1L);
        zzL = feature38;
        Feature feature39 = new Feature("nearby_connections_setting", 1L);
        zzM = feature39;
        Feature feature40 = new Feature("nearby_sharing_everyone_mode", 2L);
        zzN = feature40;
        Feature feature41 = new Feature("nearby_sharing_toggle_fast_init_notification", 1L);
        zzO = feature41;
        Feature feature42 = new Feature("nearby_sharing_batch_contacts_editing_request", 1L);
        zzP = feature42;
        Feature feature43 = new Feature("nearby_uwb", 3L);
        zzQ = feature43;
        Feature feature44 = new Feature("nearby_uwb_add_controlee", 2L);
        zzR = feature44;
        Feature feature45 = new Feature("nearby_uwb_remove_controlee", 2L);
        zzS = feature45;
        Feature feature46 = new Feature("nearby_uwb_get_chip_ids", 1L);
        zzT = feature46;
        Feature feature47 = new Feature("nearby_uwb_get_chip_infos", 1L);
        zzU = feature47;
        Feature feature48 = new Feature("nearby_uwb_add_controlee_with_session_params", 1L);
        zzV = feature48;
        Feature feature49 = new Feature("nearby_sharing_get_device_account_id", 1L);
        zzW = feature49;
        Feature feature50 = new Feature("nearby_sharing_get_intent", 2L);
        zzX = feature50;
        Feature feature51 = new Feature("nearby_sharing_get_share_targets", 1L);
        zzY = feature51;
        Feature feature52 = new Feature("nearby_sharing_sync", 2L);
        zzZ = feature52;
        Feature feature53 = new Feature("nearby_sharing_get_actions", 5L);
        zzaa = feature53;
        Feature feature54 = new Feature("nearby_sharing_opt_in_by_remote_copy", 1L);
        zzab = feature54;
        Feature feature55 = new Feature("nearby_sharing_get_opt_in_status", 1L);
        zzac = feature55;
        Feature feature56 = new Feature("nearby_sharing_qr_code", 1L);
        zzad = feature56;
        zzae = new Feature[]{feature, feature2, feature3, feature4, feature5, feature6, feature7, feature8, feature9, feature10, feature11, feature12, feature13, feature14, feature15, feature16, feature17, feature18, feature19, feature20, feature21, feature22, feature23, feature24, feature25, feature26, feature27, feature28, feature29, feature30, feature31, feature32, feature33, feature34, feature35, feature36, feature37, feature38, feature39, feature40, feature41, feature42, feature43, feature44, feature45, feature46, feature47, feature48, feature49, feature50, feature51, feature52, feature53, feature54, feature55, feature56};
    }
}
