package com.google.android.gms.internal.mlkit_translate;

import java.net.InetAddress;
import java.net.URI;
import java.net.URL;
import java.util.BitSet;
import java.util.Calendar;
import java.util.Currency;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicIntegerArray;

/* compiled from: com.google.mlkit:translate@@17.0.1 */
/* loaded from: classes4.dex */
public final class zzdr {
    public static final zzbx zzA;
    public static final zzbx zzB;
    public static final zzby zzC;
    public static final zzbx zzD;
    public static final zzby zzE;
    public static final zzbx zzF;
    public static final zzby zzG;
    public static final zzbx zzH;
    public static final zzby zzI;
    public static final zzbx zzJ;
    public static final zzby zzK;
    public static final zzbx zzL;
    public static final zzby zzM;
    public static final zzbx zzN;
    public static final zzby zzO;
    public static final zzbx zzP;
    public static final zzby zzQ;
    public static final zzbx zzR;
    public static final zzby zzS;
    public static final zzbx zzT;
    public static final zzby zzU;
    public static final zzbx zzV;
    public static final zzby zzW;
    public static final zzby zzX;
    public static final zzbx zza;
    public static final zzby zzb;
    public static final zzbx zzc;
    public static final zzby zzd;
    public static final zzbx zze;
    public static final zzbx zzf;
    public static final zzby zzg;
    public static final zzbx zzh;
    public static final zzby zzi;
    public static final zzbx zzj;
    public static final zzby zzk;
    public static final zzbx zzl;
    public static final zzby zzm;
    public static final zzbx zzn;
    public static final zzby zzo;
    public static final zzbx zzp;
    public static final zzby zzq;
    public static final zzbx zzr;
    public static final zzby zzs;
    public static final zzbx zzt;
    public static final zzbx zzu;
    public static final zzbx zzv;
    public static final zzbx zzw;
    public static final zzby zzx;
    public static final zzbx zzy;
    public static final zzbx zzz;

    static {
        zzbx zzc2 = new zzcu().zzc();
        zza = zzc2;
        zzb = new zzdg(Class.class, zzc2);
        zzbx zzc3 = new zzdf().zzc();
        zzc = zzc3;
        zzd = new zzdg(BitSet.class, zzc3);
        zzdk zzdkVar = new zzdk();
        zze = zzdkVar;
        zzf = new zzdl();
        zzg = new zzdh(Boolean.TYPE, Boolean.class, zzdkVar);
        zzdm zzdmVar = new zzdm();
        zzh = zzdmVar;
        zzi = new zzdh(Byte.TYPE, Byte.class, zzdmVar);
        zzdn zzdnVar = new zzdn();
        zzj = zzdnVar;
        zzk = new zzdh(Short.TYPE, Short.class, zzdnVar);
        zzdo zzdoVar = new zzdo();
        zzl = zzdoVar;
        zzm = new zzdh(Integer.TYPE, Integer.class, zzdoVar);
        zzbx zzc4 = new zzdp().zzc();
        zzn = zzc4;
        zzo = new zzdg(AtomicInteger.class, zzc4);
        zzbx zzc5 = new zzdq().zzc();
        zzp = zzc5;
        zzq = new zzdg(AtomicBoolean.class, zzc5);
        zzbx zzc6 = new zzck().zzc();
        zzr = zzc6;
        zzs = new zzdg(AtomicIntegerArray.class, zzc6);
        zzt = new zzcl();
        zzu = new zzcm();
        zzv = new zzcn();
        zzco zzcoVar = new zzco();
        zzw = zzcoVar;
        zzx = new zzdh(Character.TYPE, Character.class, zzcoVar);
        zzcp zzcpVar = new zzcp();
        zzy = zzcpVar;
        zzz = new zzcq();
        zzA = new zzcr();
        zzB = new zzcs();
        zzC = new zzdg(String.class, zzcpVar);
        zzct zzctVar = new zzct();
        zzD = zzctVar;
        zzE = new zzdg(StringBuilder.class, zzctVar);
        zzcv zzcvVar = new zzcv();
        zzF = zzcvVar;
        zzG = new zzdg(StringBuffer.class, zzcvVar);
        zzcw zzcwVar = new zzcw();
        zzH = zzcwVar;
        zzI = new zzdg(URL.class, zzcwVar);
        zzcx zzcxVar = new zzcx();
        zzJ = zzcxVar;
        zzK = new zzdg(URI.class, zzcxVar);
        zzcy zzcyVar = new zzcy();
        zzL = zzcyVar;
        zzM = new zzdj(InetAddress.class, zzcyVar);
        zzcz zzczVar = new zzcz();
        zzN = zzczVar;
        zzO = new zzdg(UUID.class, zzczVar);
        zzbx zzc7 = new zzda().zzc();
        zzP = zzc7;
        zzQ = new zzdg(Currency.class, zzc7);
        zzdb zzdbVar = new zzdb();
        zzR = zzdbVar;
        zzS = new zzdi(Calendar.class, GregorianCalendar.class, zzdbVar);
        zzdc zzdcVar = new zzdc();
        zzT = zzdcVar;
        zzU = new zzdg(Locale.class, zzdcVar);
        zzdd zzddVar = new zzdd();
        zzV = zzddVar;
        zzW = new zzdj(zzbo.class, zzddVar);
        zzX = new zzde();
    }
}
